@baseUrl = http://ultraflow.yanlima.com
@apiVersion = v1
@json = application/json

###############################################################################
# API V1 - USERS
# Endpoint: /api/v1/users
# Descricao: Permite criar usuários.
# Metodos permitidos: POST
###############################################################################

###
# [USERS] POST /api/v1/users - 201 Created
# Exemplo de resposta:
# {
#   "id": "123e4567-e89b-12d3-a456-426614174000",
#   "username": "yangclima",
#   "email": "yangclima@email.com",
#   "password": "senha123",
#   "created_at": "2026-03-01T12:00:00.000Z",
#   "updated_at": "2026-03-01T12:00:00.000Z"
# }
POST {{baseUrl}}/api/{{apiVersion}}/users
Accept: {{json}}
Content-Type: {{json}}

{
  "username": "yangclima",
  "email": "yangclima@gmail.com",
  "password": "senha123"
}

###
# [USERS] Resposta de erro para metodos nao permitidos - 405 MethodNotAllowedError
# Exemplo de resposta:
# {
#   "name": "MethodNotAllowedError",
#   "message": "Metodo HTTP nao permitido para este endpoint",
#   "action": "Verifique se o metodo HTTP enviado e valido para esta rota",
#   "status_code": 405
# }

###
# [USERS] GET /api/v1/users - 405 Method Not Allowed
GET {{baseUrl}}/api/{{apiVersion}}/users
Accept: {{json}}


###
# [USERS] PUT /api/v1/users - 405 Method Not Allowed
PUT {{baseUrl}}/api/{{apiVersion}}/users
Accept: {{json}}
Content-Type: {{json}}

###
# [USERS] PATCH /api/v1/users - 405 Method Not Allowed
PATCH {{baseUrl}}/api/{{apiVersion}}/users
Accept: {{json}}
Content-Type: {{json}}

###
# [USERS] DELETE /api/v1/users - 405 Method Not Allowed
DELETE {{baseUrl}}/api/{{apiVersion}}/users
Accept: {{json}}

###
# [USERS] HEAD /api/v1/users - 405 OK
HEAD {{baseUrl}}/api/{{apiVersion}}/users
Accept: {{json}}

###
# [USERS] OPTIONS /api/v1/users - 405 Method Not Allowed
OPTIONS {{baseUrl}}/api/{{apiVersion}}/users
Accept: {{json}}
